# ===== SERVER =====
server.port=8080

# ===== MONGODB =====
# Connects to local MongoDB running as a Windows service
spring.data.mongodb.uri=mongodb://localhost:27017/oceanview_resort
spring.data.mongodb.database=oceanview_resort

# ===== JWT SECURITY =====
# Secret key used to sign tokens (keep this private in real projects)
jwt.secret=OceanViewResortSecretKey2025SuperSecureJWTSigningKeyForCardiffMet
jwt.expiration=86400000

# ===== APP NAME =====
spring.application.name=ocean-view-resort

# ===== LOGGING =====
logging.level.com.oceanview=DEBUG
